### ISSUE TITLE
Fileların parquet'e çevrilmesi

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/data_engineering#3]

**Comment by simgeco** [comment]
@samozturk burada yapabilecegim bisi var mi?

**Comment by samozturk** [comment]
@simgeco aslinda ben bir script yazmistim hepsini cevirecek. ama sonrasinda patladi mi yoksa bitti mi kontrol etmedim. bir bakayim, konusuruz. pek bir sey olacagini sanmiyorum

**Comment by simgeco** [comment]
@samozturk bunu yaptik, S3'ye de attik. Kapatayim mi?

**Comment by samozturk** [comment]
@simgeco hakan'in mongosundakileri attiysan kapatabiliriz.
