### ISSUE TITLE
elastic-kibana kurulum

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/data_engineering#4]

**Comment by imranbozaci** [comment]
bu hafta sonu tamamlamamız mümkün olur mu? Değilse de mümkün olabilecek tarih, yada ihtiyacınız olacak ek desteği paylaşabilir misiniz?

**Comment by samozturk** [comment]
bu hafta kurabilecek miyiz, kurabileceksek kullanabilecek miyiz diye bakacagiz. birimiz daha cok elastic tarafindaki detaylarla ilgilenirken birimiz kibana tarafiyla iglilenir diye dusunuyorum ama duruma gore belli olacak.

**Comment by simgeco** [comment]
elastic search olmadan kibana da olmayacagi icin iletisimde kalacagiz 😅
