### ISSUE TITLE
watcher, forkcounts e.g gibi verilerin githubdan alınması

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/data_engineering#6]

**Comment by imranbozaci** [comment]
@hcipek  bunu haftasonuna tamamlamamız mümkün olabilir mi?
Birde hangi veriler var basit bir listeyle hızlıca paylaşabilir misin, excel vs.fln olabilir, ona göre analiz kapsamını da planlayalım
@samozturk  the watcher:)

**Comment by hcipek** [comment]
Tüm Commitlerin oluşmasını bekliyorum, daha kısa bir işlem için.
Cumartesi geceye done olur.
