### ISSUE TITLE
commit hash bilgisi parse edilerek, date vs. datalarının alınması

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/data_engineering#7]

**Comment by imranbozaci** [comment]
bunu ne zamana tamamlyabiliriz? alabildiğimiz dataların da kısaca bir listesini paylaşabilir misiniz?
@hcipek @samozturk

**Comment by samozturk** [comment]
dun gece program yine fail oldu. o yuzden once merge, sonra bu datalari cekme yoluna gidelim diye dusundum.

**Comment by hcipek** [comment]
Mevcutta devam ediyor. (Est. 19.03.22 Gece)

Mongo Express üzerinden Commits içerisindeki datalardan fikir edinebilirsiniz.
