### ISSUE TITLE
Monitoring ortamının kurulması

### ISSUE THREAD

**Issue by imranbozaci** [ITU-Apollo/data_engineering#8]

**Comment by imranbozaci** [comment]
@samozturk  burda yaptığın işi birkaç cümle ile özetleyebilir misin?Altan hocaya sunumlarda bunu da öne çıkarmak istiyorm

**Comment by samozturk** [comment]
Burada kullanilan iki adet tool var.

1. Prometheus
Bu arkadas, windowstaki crlt+alt+delete ile acilan task manager gibi hem calisan processleri hem de cpu, memory, disk, network gibi sistem seviyesindeki metrikleri topluyor ve bir time-series database'ine yaziyor. Istersek degerleri :9090 portundan gorebiliyoruz. Ayni zamanda dagitik bir sekilde baska serverlarin metriklerini de ana bir server'da gorebiliyoruz.

2. Grafana
Bu arkadas kendine gosterilen data sourcelari gorsellestirmek ile mukellef. Kibana gibi fakat time series datalarini gorsellestiriyor. MYSQL datalarini da time series fieldi ekleyerek gorsellestirmek mumkun. BIzim case'imizde bir prometheus'taki metricleri monitor ediyoruz. 

Bonus: Prometheus Alert Manager yukledim. Ayni zamanda servera bir SMTP(Simple mail transfer protocol) serveri kurdum. Eger memory azalirsa, disk cosarsa ya da instancelarimiz offline olursa notification aliyorum mail kutuma. Esas havali olan kisim burasi bence.
